# **ISL League Table Predictions**

## **Initials**

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [ ]:
data_ = pd.read_csv('/content/ISL ML - Sheet1.csv')

In [ ]:
data_

Season             Club  ...  Won ISL Last season  League table finish
0     2019              ATK  ...                    0                    2
1     2019    Bengaluru FC   ...                    1                    3
2     2019     ChennaiyinFC  ...                    0                    4
3     2019  Kerala Blasters  ...                    0                    7
4     2019        Odisha Fc  ...                    0                    6
5     2019           FC Goa  ...                    0                    1
6     2019            NEUFC  ...                    0                    9
7     2019    Jamshedpur FC  ...                    0                    8
8     2019     Hyderabad FC  ...                    0                   10
9     2019   Mumbai City FC  ...                    0                    5
10    2018              ATK  ...                    0                    6
11    2018    Bengaluru FC   ...                    0                    1
12    2018     ChennaiyinFC  ...                    1                   10
13    2018  Kerala Blasters  ...                    0                    9
14    2018        Odisha Fc  ...                    0                    8
15    2018           FC Goa  ...                    0                    2
16    2018            NEUFC  ...                    0                    4
17    2018    Jamshedpur FC  ...                    0                    5
18    2018     Hyderabad FC  ...                    0                    7
19    2018   Mumbai City FC  ...                    0                    3
20    2017              ATK  ...                    1                    9
21    2017     ChennaiyinFC  ...                    0                    2
22    2017  Kerala Blasters  ...                    0                    7
23    2017        Odisha Fc  ...                    0                    8
24    2017           FC Goa  ...                    0                    3
25    2017            NEUFC  ...                    0                   10
26    2017     Hyderabad FC  ...                    0                    4
27    2017   Mumbai City FC  ...                    0                    7
28    2016              ATK  ...                    0                    4
29    2016     ChennaiyinFC  ...                    1                    7
30    2016  Kerala Blasters  ...                    0                    2
31    2016        Odisha Fc  ...                    0                    3
32    2016           FC Goa  ...                    0                    8
33    2016            NEUFC  ...                    0                    5
34    2016     Hyderabad FC  ...                    0                    6
35    2016   Mumbai City FC  ...                    0                    1
36    2015              ATK  ...                    1                    2
37    2015     ChennaiyinFC  ...                    0                    3
38    2015  Kerala Blasters  ...                    0                    8
39    2015        Odisha Fc  ...                    0                    4
40    2015           FC Goa  ...                    0                    1
41    2015            NEUFC  ...                    0                    5
42    2015     Hyderabad FC  ...                    0                    7
43    2015   Mumbai City FC  ...                    0                    6

[44 rows x 13 columns]

In [ ]:
x = data_.iloc[:,1:-4 ]
x.shape

(44, 8)

In [ ]:
X_2 = data_.iloc[:,-4:-1]
X_2

Club Value(Million rupees)  Final Played Last season  Won ISL Last season
0                       504.10                         0                    0
1                       443.68                         1                    1
2                       331.21                         0                    0
3                       414.52                         0                    0
4                       364.53                         0                    0
5                       404.10                         1                    0
6                       454.03                         0                    0
7                       314.53                         0                    0
8                       383.27                         0                    0
9                       374.94                         0                    0
10                      477.03                         0                    0
11                      493.67                         1                    0
12                      377.05                         1                    1
13                      362.44                         0                    0
14                      406.19                         0                    0
15                      468.68                         0                    0
16                      479.09                         0                    0
17                      364.55                         0                    0
18                      408.27                         0                    0
19                      429.10                         0                    0
20                      420.77                         1                    1
21                      310.66                         0                    0
22                      302.05                         1                    0
23                      318.70                         0                    0
24                      397.90                         0                    0
25                      422.85                         0                    0
26                      318.70                         0                    0
27                      233.30                         0                    0
28                      516.59                         0                    0
29                      302.36                         1                    1
30                      252.04                         0                    0
31                      335.36                         0                    0
32                      368.69                         1                    0
33                      364.53                         0                    0
34                      441.60                         0                    0
35                      329.11                         0                    0
36                      727.00                         1                    1
37                      333.28                         0                    0
38                      260.38                         1                    0
39                      189.55                         0                    0
40                      368.69                         0                    0
41                      466.69                         0                    0
42                      810.29                         0                    0
43                      572.83                         0                    0

In [ ]:
y = data_.iloc[:, -1]
y

0      2
1      3
2      4
3      7
4      6
5      1
6      9
7      8
8     10
9      5
10     6
11     1
12    10
13     9
14     8
15     2
16     4
17     5
18     7
19     3
20     9
21     2
22     7
23     8
24     3
25    10
26     4
27     7
28     4
29     7
30     2
31     3
32     8
33     5
34     6
35     1
36     2
37     3
38     8
39     4
40     1
41     5
42     7
43     6
Name: League table finish, dtype: int64

In [ ]:
x.join(x, y, how='inner')


Club  Arrivals  ...  Foreign Players   League table finish
0               ATK        20  ...                 9                    2
1     Bengaluru FC         12  ...                11                    3
2      ChennaiyinFC        11  ...                 7                    4
3   Kerala Blasters        28  ...                 8                    7
4         Odisha Fc        13  ...                 8                    6
5            FC Goa        11  ...                 6                    1
6             NEUFC        19  ...                10                    9
7     Jamshedpur FC        15  ...                 7                    8
8      Hyderabad FC        24  ...                 7                   10
9    Mumbai City FC        14  ...                 7                    5
10              ATK        35  ...                 9                    6
11    Bengaluru FC         19  ...                 9                    1
12     ChennaiyinFC        22  ...                 8                   10
13  Kerala Blasters        24  ...                 7                    9
14        Odisha Fc        20  ...                 8                    8
15           FC Goa        16  ...                 8                    2
16            NEUFC        19  ...                 9                    4
17    Jamshedpur FC        19  ...                 7                    5
18     Hyderabad FC        19  ...                 8                    7
19   Mumbai City FC        20  ...                 7                    3
20              ATK         6  ...                11                    9
21     ChennaiyinFC        23  ...                 8                    2
22  Kerala Blasters         8  ...                10                    7
23        Odisha Fc         8  ...                 9                    8
24           FC Goa        10  ...                10                    3
25            NEUFC        15  ...                11                   10
26     Hyderabad FC        18  ...                10                    4
27   Mumbai City FC         9  ...                 8                    7
28              ATK        23  ...                 9                    4
29     ChennaiyinFC        28  ...                11                    7
30  Kerala Blasters        31  ...                10                    2
31        Odisha Fc        27  ...                11                    3
32           FC Goa        23  ...                10                    8
33            NEUFC        28  ...                12                    5
34     Hyderabad FC        26  ...                11                    6
35   Mumbai City FC        29  ...                11                    1
36              ATK        28  ...                11                    2
37     ChennaiyinFC        30  ...                11                    3
38  Kerala Blasters        25  ...                11                    8
39        Odisha Fc        24  ...                11                    4
40           FC Goa        28  ...                12                    1
41            NEUFC        28  ...                14                    5
42     Hyderabad FC        29  ...                11                    7
43   Mumbai City FC        27  ...                11                    6

[44 rows x 9 columns]

In [ ]:
Y_2018 = y[10:20,]
Y_2018

10     6
11     1
12    10
13     9
14     8
15     2
16     4
17     5
18     7
19     3
Name: League table finish, dtype: int64

In [ ]:
x.shape

(44, 8)

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ColTran = ColumnTransformer(transformers= [('encoder', OneHotEncoder(), [0])], remainder = 'passthrough')
X = np.array(ColTran.fit_transform(x))

In [ ]:
X

array([[ 1.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   , 20.   , 18.   ,  1.   , 31.   ,  6.   ,  4.8  ,
         9.   ],
       [ 0.   ,  1.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   , 12.   , 15.   ,  0.   , 34.   ,  1.   ,  0.5  ,
        11.   ],
       [ 0.   ,  0.   ,  1.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   , 11.   , 15.   ,  0.   , 25.   , 10.   ,  4.6  ,
         7.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  1.   ,  0.   ,
         0.   ,  0.   , 28.   , 20.   ,  1.   , 34.   ,  9.   ,  6.   ,
         8.   ],
       [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  1.   , 13.   , 12.   ,  0.   , 27.   ,  8.   ,  5.6  ,
         8.   ],
       [ 0.   ,  0.   ,  0.   ,  1.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   , 11.   ,  7.   ,  0.   , 26.   ,  2.   ,  3.2  ,
         6.   ],
       [ 0.   ,  0.   ,  0.   ,  0

In [ ]:
X_pd = pd.DataFrame(X)
X_pd

0    1    2    3    4    5    6   ...    10    11   12    13    14     15    16
0   1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  20.0  18.0  1.0  31.0   6.0  4.800   9.0
1   0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  12.0  15.0  0.0  34.0   1.0  0.500  11.0
2   0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  11.0  15.0  0.0  25.0  10.0  4.600   7.0
3   0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  28.0  20.0  1.0  34.0   9.0  6.000   8.0
4   0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  13.0  12.0  0.0  27.0   8.0  5.600   8.0
5   0.0  0.0  0.0  1.0  0.0  0.0  0.0  ...  11.0   7.0  0.0  26.0   2.0  3.200   6.0
6   0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  19.0  17.0  1.0  30.0   4.0  6.400  10.0
7   0.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  15.0  18.0  1.0  26.0   5.0  5.000   7.0
8   0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  24.0   6.0  1.0  33.0   7.0  6.000   7.0
9   0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  14.0  15.0  0.0  28.0   3.0  4.800   7.0
10  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  35.0  29.0  1.0  33.0   9.0  4.500   9.0
11  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  19.0  18.0  0.0  33.0   1.0  1.000   9.0
12  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  22.0  21.0  0.0  30.0   2.0  3.250   8.0
13  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  24.0  21.0  1.0  34.0   7.0  5.250   7.0
14  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  20.0  19.0  1.0  28.0   8.0  5.000   8.0
15  0.0  0.0  0.0  1.0  0.0  0.0  0.0  ...  16.0  15.0  0.0  26.0   3.0  3.500   8.0
16  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  19.0  24.0  1.0  27.0  10.0  7.000   9.0
17  0.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  19.0  20.0  1.0  28.0   5.0  5.000   7.0
18  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  19.0  21.0  1.0  33.0   4.0  5.750   8.0
19  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  20.0  23.0  0.0  29.0   7.0  5.250   7.0
20  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   6.0  32.0  1.0  31.0   4.0  3.000  11.0
21  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  23.0   8.0  1.0  32.0   7.0  3.660   8.0
22  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...   8.0  33.0  1.0  34.0   2.0  4.660  10.0
23  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   8.0  27.0  1.0  27.0   3.0  4.000   9.0
24  0.0  0.0  0.0  1.0  0.0  0.0  0.0  ...  10.0  29.0  1.0  29.0   8.0  3.660  10.0
25  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  15.0  30.0  1.0  27.0   5.0  6.000  11.0
26  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  18.0  39.0  1.0  33.0   6.0  6.333  10.0
27  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   9.0  26.0  0.0  25.0   1.0  4.667   8.0
28  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  23.0  28.0  1.0  25.0   2.0  2.500   9.0
29  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  28.0  28.0  0.0  29.0   3.0  2.000  11.0
30  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  31.0  28.0  1.0  27.0   8.0  6.000  10.0
31  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  27.0  28.0  1.0  26.0   4.0  4.500  11.0
32  0.0  0.0  0.0  1.0  0.0  0.0  0.0  ...  23.0  27.0  0.0  24.0   1.0  1.500  10.0
33  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  28.0  34.0  1.0  26.0   5.0  6.500  12.0
34  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  26.0  28.0  1.0  25.0   7.0  6.500  11.0
35  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  29.0  26.0  1.0  29.0   6.0  6.500  11.0
36  1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  28.0  26.0  0.0  29.0   3.0  3.000  11.0
37  0.0  0.0  1.0  0.0  0.0  0.0  0.0  ...  30.0  33.0  0.0  29.0   1.0  1.000  11.0
38  0.0  0.0  0.0  0.0  0.0  0.0  1.0  ...  25.0  29.0  1.0  28.0   4.0  4.000  11.0
39  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  24.0  26.0  0.0  28.0   5.0  5.000  11.0
40  0.0  0.0  0.0  1.0  0.0  0.0  0.0  ...  28.0  28.0  0.0  27.0   2.0  2.000  12.0
41  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  28.0  28.0  0.0  28.0   8.0  8.000  14.0
42  0.0  0.0  0.0  0.0  1.0  0.0  0.0  ...  29.0  29.0  1.0  26.0   6.0  6.000  11.0
43  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  27.0  27.0  1.0  26.0   7.0  7.000  11.0

[44 rows x 17 columns]

In [ ]:
X_full = X_pd.join(X_2)
X_full

0    1  ...  Final Played Last season  Won ISL Last season
0   1.0  0.0  ...                         0                    0
1   0.0  1.0  ...                         1                    1
2   0.0  0.0  ...                         0                    0
3   0.0  0.0  ...                         0                    0
4   0.0  0.0  ...                         0                    0
5   0.0  0.0  ...                         1                    0
6   0.0  0.0  ...                         0                    0
7   0.0  0.0  ...                         0                    0
8   0.0  0.0  ...                         0                    0
9   0.0  0.0  ...                         0                    0
10  1.0  0.0  ...                         0                    0
11  0.0  1.0  ...                         1                    0
12  0.0  0.0  ...                         1                    1
13  0.0  0.0  ...                         0                    0
14  0.0  0.0  ...                         0                    0
15  0.0  0.0  ...                         0                    0
16  0.0  0.0  ...                         0                    0
17  0.0  0.0  ...                         0                    0
18  0.0  0.0  ...                         0                    0
19  0.0  0.0  ...                         0                    0
20  1.0  0.0  ...                         1                    1
21  0.0  0.0  ...                         0                    0
22  0.0  0.0  ...                         1                    0
23  0.0  0.0  ...                         0                    0
24  0.0  0.0  ...                         0                    0
25  0.0  0.0  ...                         0                    0
26  0.0  0.0  ...                         0                    0
27  0.0  0.0  ...                         0                    0
28  1.0  0.0  ...                         0                    0
29  0.0  0.0  ...                         1                    1
30  0.0  0.0  ...                         0                    0
31  0.0  0.0  ...                         0                    0
32  0.0  0.0  ...                         1                    0
33  0.0  0.0  ...                         0                    0
34  0.0  0.0  ...                         0                    0
35  0.0  0.0  ...                         0                    0
36  1.0  0.0  ...                         1                    1
37  0.0  0.0  ...                         0                    0
38  0.0  0.0  ...                         1                    0
39  0.0  0.0  ...                         0                    0
40  0.0  0.0  ...                         0                    0
41  0.0  0.0  ...                         0                    0
42  0.0  0.0  ...                         0                    0
43  0.0  0.0  ...                         0                    0

[44 rows x 20 columns]

In [ ]:
from sklearn.preprocessing import StandardScaler

scale = StandardScaler()
X_Scale = scale.fit_transform(X_full)
X_Scale.shape

(44, 20)

In [ ]:
X_Scale_2018= X_Scale[10:20, :]
X_Scale_2018

array([[ 2.79284801, -0.21821789, -0.35805744, -0.35805744, -0.35805744,
        -0.21821789, -0.35805744, -0.35805744, -0.35805744, -0.35805744,
         1.97760611,  0.75287028,  0.79349205,  1.4495253 ,  1.52796424,
        -0.23046638, -0.54232614, -0.35805744],
       [-0.35805744,  4.58257569, -0.35805744, -0.35805744, -0.35805744,
        -0.21821789, -0.35805744, -0.35805744, -0.35805744, -0.35805744,
        -0.23580359, -0.73443264, -1.26025208,  1.4495253 , -1.51069911,
        -0.23046638,  1.84390889, -0.35805744],
       [-0.35805744, -0.21821789,  2.79284801, -0.35805744, -0.35805744,
        -0.21821789, -0.35805744, -0.35805744, -0.35805744, -0.35805744,
         0.17921073, -0.32880457, -1.26025208,  0.42633097, -1.13086619,
        -0.79382866,  1.84390889,  2.79284801],
       [-0.35805744, -0.21821789, -0.35805744, -0.35805744, -0.35805744,
        -0.21821789,  2.79284801, -0.35805744, -0.35805744, -0.35805744,
         0.45588694, -0.32880457,  0.79349205,  1.790

## **Training Part**

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size= 0.2, random_state=0)

In [ ]:
X_train.shape

(35, 17)

In [ ]:
X_test.shape

(9, 17)

In [ ]:
Y_train.shape

(35,)

In [ ]:
Y_test.shape

(9,)

In [ ]:
import tensorflow as tf

In [ ]:
import tensorflow as tf
model = tf.keras.models.Sequential([
                                   # First Hidden Layer
                                   tf.keras.layers.Dense(units=16,input_dim = 20, activation='relu'),
                                   tf.keras.layers.Dense(units= 18, activation='relu'),
                                   
                                   
                                   # Output Layer 
                                   tf.keras.layers.Dense(units=1)

])

In [ ]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 16)                288       
_________________________________________________________________
dense_4 (Dense)              (None, 18)                306       
_________________________________________________________________
dense_5 (Dense)              (None, 1)                 19        
Total params: 613
Trainable params: 613
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.compile(
    optimizer= 'adam',
    loss = 'mean_squared_error'
)

In [ ]:
history = model.fit(X_train, Y_train , steps_per_epoch=10, epochs=300, verbose=1)

Epoch 1/275
10/10 [==============================] - 0s 2ms/step - loss: 3.2308
Epoch 2/275
10/10 [==============================] - 0s 2ms/step - loss: 0.7770
Epoch 3/275
10/10 [==============================] - 0s 2ms/step - loss: 1.7148
Epoch 4/275
10/10 [==============================] - 0s 2ms/step - loss: 1.0711
Epoch 5/275
10/10 [==============================] - 0s 2ms/step - loss: 0.9563
Epoch 6/275
10/10 [==============================] - 0s 2ms/step - loss: 0.9747
Epoch 7/275
10/10 [==============================] - 0s 2ms/step - loss: 0.6532
Epoch 8/275
10/10 [==============================] - 0s 2ms/step - loss: 0.9162
Epoch 9/275
10/10 [==============================] - 0s 2ms/step - loss: 0.7147
Epoch 10/275
10/10 [==============================] - 0s 2ms/step - loss: 0.7505
Epoch 11/275
10/10 [==============================] - 0s 2ms/step - loss: 0.6428
Epoch 12/275
10/10 [==============================] - 0s 2ms/step - loss: 0.5683
Epoch 13/275
10/10 [=================

In [ ]:
model.save('/content/drive/My Drive/Machine learning')

Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
Instructions for updating:
This property should not be used in TensorFlow 2.0, as updates are applied automatically.
INFO:tensorflow:Assets written to: /content/drive/My Drive/Machine learning/assets


## **Testing**

In [ ]:
from tensorflow import keras
model_ISL = keras.models.load_model('/content/drive/My Drive/Machine learning/Isl2/')

In [ ]:
Y_predict_ATK = model_ISL.predict(scale.transform([[1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 8., 3.,  0.,
        29.,  2., 4.3, 8.,460.34,  1.,  1.]]))
Y_predict_ATK

array([[4.986812]], dtype=float32)

In [ ]:
Y_predict_ATK = model_ISL.predict(scale.transform([[1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 8., 3.,  0.,
        29.,  2., 4.3, 8.,460.34,  1.,  1.]]))
Y_predict_ATK

array([[4.986812]], dtype=float32)

In [ ]:
Y_predict_BFC = model_ISL.predict(scale.transform([[0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 13., 12.,  0.,
        32.,  3., 1.66, 7.,437.43,  0.,  0.]]))
Y_predict_BFC

array([[0.56777054]], dtype=float32)

In [ ]:
Y_predict_CFC = model_ISL.predict(scale.transform([[ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 12.,  9.,  1.,
        28.,  4., 4.5,  7.,383.37,  1.,  1.]]))
Y_predict_CFC

array([[11.704152]], dtype=float32)

In [ ]:
Y_predict_KBFC = model_ISL.predict(scale.transform([[0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0., 19., 26.,  1.,
        31.,  7.,6.166,  7.,539.5,  0.,  0.]]))
Y_predict_KBFC

array([[7.9786263]], dtype=float32)

In [ ]:
Y_predict_OFC = model_ISL.predict(scale.transform([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1., 23., 12.,  1.,
        35.,  6., 5.66, 7., 410.35, 0.,  0.]]))
Y_predict_OFC

array([[5.741554]], dtype=float32)

In [ ]:
Y_predict_FCGoa = model_ISL.predict(scale.transform([[ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0., 17., 15.,  1.,
        30.,  1., 2.833, 6., 368.69,  0.,  0.]]))
Y_predict_FCGoa

array([[1.4994646]], dtype=float32)

In [ ]:
Y_predict_NEUFC = model_ISL.predict(scale.transform([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0., 21., 12.,  1.,
        30.,  9.,6.833,  7.,374.94,  0.,  0.]]))
Y_predict_NEUFC

array([[8.004615]], dtype=float32)

In [ ]:
Y_predict_JFC = model_ISL.predict(scale.transform([[ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0., 22., 12.,  1.,
        34.,  8., 6, 7.,343.7,  0.,  0.]]))
Y_predict_JFC

array([[4.4777203]], dtype=float32)

In [ ]:
Y_predict_HFC = model_ISL.predict(scale.transform([[  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0., 20., 18.,  1.,
        33., 10.,6.67,  7.,366.61,  0.,  0.]]))
Y_predict_HFC

array([[8.58872]], dtype=float32)

In [ ]:
Y_predict_MCFC = model_ISL.predict(scale.transform([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0., 19., 20.,  1.,
        28.,  5.,4.83,  7.,443.7,  0.,  0.]]))
Y_predict_MCFC

array([[5.009756]], dtype=float32)

In [ ]:
Y_predict_EBFC = model_ISL.predict(scale.transform([[0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 35., 19.,  1.,
        36.,  0, 0, 7.,458.26,  0.,  0.]]))
Y_predict_EBFC

array([[7.4755044]], dtype=float32)

In [ ]:
ISL_clubs = ['ATK MohunBagan', 'Kerala Blasters', 'Bengaluru FC', 'Chennaiyin Fc', 'Odisha FC', 'NEUFC', 'SC East Bengal','FC Goa', 'Hyderabad FC', 'Jamshedpur FC', 'Mumbai City FC' ]
Position = [Y_predict_ATK,  Y_predict_KBFC,  Y_predict_BFC, Y_predict_CFC,Y_predict_OFC,Y_predict_NEUFC, Y_predict_EBFC,Y_predict_FCGoa,Y_predict_HFC,Y_predict_JFC,  Y_predict_MCFC ]
p = np.round(Position)
ISL = {'Club': ISL_clubs, 'Position':list(p)}
ISL

{'Club': ['ATK MohunBagan',
  'Kerala Blasters',
  'Bengaluru FC',
  'Chennaiyin Fc',
  'Odisha FC',
  'NEUFC',
  'SC East Bengal',
  'FC Goa',
  'Hyderabad FC',
  'Jamshedpur FC',
  'Mumbai City FC'],
 'Position': [array([[5.]], dtype=float32),
  array([[8.]], dtype=float32),
  array([[1.]], dtype=float32),
  array([[12.]], dtype=float32),
  array([[6.]], dtype=float32),
  array([[8.]], dtype=float32),
  array([[7.]], dtype=float32),
  array([[1.]], dtype=float32),
  array([[9.]], dtype=float32),
  array([[4.]], dtype=float32),
  array([[5.]], dtype=float32)]}

In [ ]:
ISL_20_table = pd.DataFrame.from_dict(ISL)
ISL_20_table.sort_values('Position')

Club  Position
2      Bengaluru FC   [[1.0]]
7            FC Goa   [[1.0]]
9     Jamshedpur FC   [[4.0]]
0    ATK MohunBagan   [[5.0]]
10   Mumbai City FC   [[5.0]]
4         Odisha FC   [[6.0]]
6    SC East Bengal   [[7.0]]
1   Kerala Blasters   [[8.0]]
5             NEUFC   [[8.0]]
8      Hyderabad FC   [[9.0]]
3     Chennaiyin Fc  [[12.0]]